# Generated by Django 5.1.1 on 2024-09-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VivApp', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
