# Generated by Django 5.1.1 on 2024-09-30 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivApp', '0005_alumni_current_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_image', models.ImageField(upload_to='donation_images/')),
                ('total_donation_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_donation_done', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('project_description', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
            ],
        ),
    ]
