# Generated by Django 5.1.1 on 2024-09-30 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivApp', '0008_adding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=45)),
                ('event_description', models.CharField(max_length=500)),
            ],
        ),
    ]
